import { oneDark } from "@codemirror/theme-one-dark"

import {
  abcdef as abcdef_alt,
  abyss as abyss_alt,
  androidStudio as androidstudio_alt,
  andromeda as andromeda_alt,
  basicDark as basicDark_alt,
  basicLight as basicLight_alt,
  catppuccinMocha,
  cobalt2,
  forest,
  githubDark as githubDark_alt,
  githubLight as githubLight_alt,
  gruvboxDark as gruvboxDark_alt,
  gruvboxLight as gruvboxLight_alt,
  highContrastDark,
  highContrastLight,
  materialDark as materialDark_alt,
  materialLight as materialLight_alt,
  monokai as monokai_alt,
  nord as nord_alt,
  palenight,
  solarizedDark as solarizedDark_alt,
  solarizedLight as solarizedLight_alt,
  synthwave84,
  tokyoNightDay as tokyoNightDay_alt,
  tokyoNightStorm as tokyoNightStorm_alt,
  volcano,
  vsCodeDark as vscodeDark_alt,
  vsCodeLight as vscodeLight_alt,
} from "@fsegurai/codemirror-theme-bundle"
import {
  abcdef,
  abyss,
  androidstudio,
  andromeda,
  atomone,
  aura,
  basicDark,
  basicLight,
  bbedit,
  bespin,
  consoleDark,
  consoleLight,
  copilot,
  darcula,
  dracula,
  duotoneDark,
  duotoneLight,
  eclipse,
  githubDark,
  githubLight,
  gruvboxDark,
  gruvboxLight,
  kimbie,
  materialDark,
  materialLight,
  monokai,
  monokaiDimmed,
  noctisLilac,
  nord,
  okaidia,
  quietlight,
  red,
  solarizedDark,
  solarizedLight,
  sublime,
  tokyoNight,
  tokyoNightDay,
  tokyoNightStorm,
  tomorrowNightBlue,
  vscodeDark,
  vscodeLight,
  whiteDark,
  whiteLight,
  xcodeDark,
  xcodeLight,
} from "@uiw/codemirror-themes-all"

/**
 * Extensions provided by Editor Themes.
 */
export namespace Extensions {
  /**
   * Themes from `react-codemirror`, `@fsegurai/codemirror-themes`, and `@codemirror/theme-one-dark`.
   *
   * @see EditorView.theme
   */
  export const themes = {
    abcdef,
    abcdef_alt,
    abyss,
    abyss_alt,
    androidstudio,
    androidstudio_alt,
    andromeda,
    andromeda_alt,
    atomone,
    aura,
    basicDark,
    basicDark_alt,
    basicLight,
    basicLight_alt,
    bbedit,
    bespin,
    catppuccinMocha,
    cobalt2,
    consoleDark,
    consoleLight,
    copilot,
    darcula,
    dracula,
    duotoneDark,
    duotoneLight,
    eclipse,
    forest,
    githubDark,
    githubDark_alt,
    githubLight,
    githubLight_alt,
    gruvboxDark,
    gruvboxDark_alt,
    gruvboxLight,
    gruvboxLight_alt,
    highContrastDark,
    highContrastLight,
    kimbie,
    materialDark,
    materialDark_alt,
    materialLight,
    materialLight_alt,
    monokai,
    monokai_alt,
    monokaiDimmed,
    noctisLilac,
    nord,
    nord_alt,
    okaidia,
    oneDark,
    palenight,
    quietlight,
    red,
    solarizedDark,
    solarizedDark_alt,
    solarizedLight,
    solarizedLight_alt,
    sublime,
    synthwave84,
    tokyoNight,
    tokyoNightDay,
    tokyoNightDay_alt,
    tokyoNightStorm,
    tokyoNightStorm_alt,
    tomorrowNightBlue,
    volcano,
    vscodeDark,
    vscodeDark_alt,
    vscodeLight,
    vscodeLight_alt,
    whiteDark,
    whiteLight,
    xcodeDark,
    xcodeLight,
  } as const
}
