/**
 * Settings for the {@link JoplinPlugin}.
 *
 * Currently, this is a duplicate of the CodeMirror extension {@link Config}.
 * This duplication exists to decouple the Joplin plugin from the CodeMirror extension.
 *
 * @see Config
 */
export interface PluginSettings {
  readonly theme:
    | "abcdef"
    | "abcdef_alt"
    | "abyss"
    | "abyss_alt"
    | "androidstudio"
    | "androidstudio_alt"
    | "andromeda"
    | "andromeda_alt"
    | "atomone"
    | "aura"
    | "basicDark"
    | "basicDark_alt"
    | "basicLight"
    | "basicLight_alt"
    | "bbedit"
    | "bespin"
    | "catppuccinMocha"
    | "cobalt2"
    | "consoleDark"
    | "consoleLight"
    | "copilot"
    | "darcula"
    | "dracula"
    | "duotoneDark"
    | "duotoneLight"
    | "eclipse"
    | "forest"
    | "githubDark"
    | "githubDark_alt"
    | "githubLight"
    | "githubLight_alt"
    | "gruvboxDark"
    | "gruvboxDark_alt"
    | "gruvboxLight"
    | "gruvboxLight_alt"
    | "highContrastDark"
    | "highContrastLight"
    | "kimbie"
    | "materialDark"
    | "materialDark_alt"
    | "materialLight"
    | "materialLight_alt"
    | "monokai"
    | "monokai_alt"
    | "monokaiDimmed"
    | "noctisLilac"
    | "nord"
    | "nord_alt"
    | "okaidia"
    | "oneDark"
    | "palenight"
    | "quietlight"
    | "red"
    | "solarizedDark"
    | "solarizedDark_alt"
    | "solarizedLight"
    | "solarizedLight_alt"
    | "sublime"
    | "synthwave84"
    | "tokyoNight"
    | "tokyoNightDay"
    | "tokyoNightDay_alt"
    | "tokyoNightStorm"
    | "tokyoNightStorm_alt"
    | "tomorrowNightBlue"
    | "volcano"
    | "vscodeDark"
    | "vscodeDark_alt"
    | "vscodeLight"
    | "vscodeLight_alt"
    | "whiteDark"
    | "whiteLight"
    | "xcodeDark"
    | "xcodeLight"
}
